Added the rest of the methods, moved things around

diff --git a/api/Makefile b/api/Makefile
--- a/api/Makefile
+++ b/api/Makefile
@@ -1,11 +1,11 @@
 SHELL = /bin/bash
 MAKEFLAGS+=-s
-BINARY = mboard
+BINARY = build/api
 TEST_DIRECTORIES = ./handlers ./services
 
 $(BINARY):
-	go build -o $(BINARY)
-	echo "Binary:" $(CURDIR)/$(BINARY)
+	go build -o $(BINARY) cmd/main.go
+	echo $(BINARY)
 
 install:
 	which glide > /dev/null || { echo "glide not found. run brew install glide"; exit 1; }
@@ -19,5 +19,10 @@ test:
 
 clean:
 	if [ -f $(BINARY) ]; then rm $(BINARY); fi
+
+container:
+	which docker > /dev/null || { echo "Docker not found."; exit 1; }
+	docker build -t mboard/api:latest .
+	docker tag mboard/api:latest gcr.io/mboard-kub/api
 
 .PHONY: clean install test testv
diff --git a/posts/Makefile b/posts/Makefile
--- a/posts/Makefile
+++ b/posts/Makefile
@@ -1,11 +1,11 @@
 SHELL = /bin/bash
 MAKEFLAGS+=-s
-BINARY = service
+BINARY = build/service
 TEST_DIRECTORIES = ./ 
 
 $(BINARY):
-	go build -o $(BINARY)
-	echo "Binary:" $(CURDIR)/$(BINARY)
+	go build -o $(BINARY) cmd/main.go
+	echo $(BINARY)
 
 install:
 	which glide > /dev/null || { echo "glide not found. run brew install glide"; exit 1; }
@@ -20,8 +20,13 @@ test:
 clean:
 	if [ -f $(BINARY) ]; then rm $(BINARY); fi
 
+container:
+	which docker > /dev/null || { echo "Docker not found."; exit 1; }
+	docker build -t mboard/posts:latest .
+	docker tag mboard/posts:latest gcr.io/mboard-kub/posts
+
 proto:
 	which protoc > /dev/null || { echo "protoc not found."; exit 1; }
 	protoc pb/*.proto --go_out=plugins=grpc:.
 
-.PHONY: clean install test testv proto
+.PHONY: clean install test testv proto container
